[pytest]
pythonpath = .
testpaths = test
addopts = -v --tb=short
markers =
    AnswerRelevancy: Realiza todos os testes envolvendo Answer Relevancy
    Faithfulness:  Realiza todos os testes envolvendo Faithfulness 
    GEval:  Realiza todos os testes envolvendo GEval
